version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "6101:6101"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:16-alpine
    command:
      - "postgres"
      - "-c"
      - "port=6101"